baseurl = "/"
title = "attachmentgenie.com"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "yourdiscussshortname"

[params]
    author = "Bram Vogelaar"
    description = "Bram Vogelaar's personal website"
    keywords = "blog,developer,personal"
    info = "Open Source Consultant"
    avatarurl = "images/avatar.jpg"
    dateformat = "January 2, 2006"
    hideCredits = false
    hideCopyright = false
    commit = "https://github.com/luizdepra/hugo-coder/tree/"
    rtl = false
    inverted = false
    maxSeeAlsoItems = 5
    custom_css = []
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/attachmentgenie/"
[[params.social]]
    name = "Slideshare"
    icon = "fab fa-slideshare"
    weight = 1
    url = "https://www.slideshare.net/attachmentgenie/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/attachmentgenie/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/bram-vogelaar-2316578/"

[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

